// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1rhCDuGz0G7x5hngipWbm10_XYFlbwA',
    appId: '1:499402471592:web:53026ce15c61ba2bcf2a9d',
    messagingSenderId: '499402471592',
    projectId: 'bnch-9456f',
    authDomain: 'bnch-9456f.firebaseapp.com',
    databaseURL: 'https://bnch-9456f-default-rtdb.firebaseio.com',
    storageBucket: 'bnch-9456f.appspot.com',
    measurementId: 'G-BLRJ158S85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuv05VmFODsBV31qPLYnys5pLN7MUr8hA',
    appId: '1:499402471592:android:fefc0c8f6a2f077ccf2a9d',
    messagingSenderId: '499402471592',
    projectId: 'bnch-9456f',
    databaseURL: 'https://bnch-9456f-default-rtdb.firebaseio.com',
    storageBucket: 'bnch-9456f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlc-9LnhG1eivAPcVRSDLXEwNhaL-sRk',
    appId: '1:499402471592:ios:16b20db27f2fee3acf2a9d',
    messagingSenderId: '499402471592',
    projectId: 'bnch-9456f',
    databaseURL: 'https://bnch-9456f-default-rtdb.firebaseio.com',
    storageBucket: 'bnch-9456f.appspot.com',
    iosClientId: '499402471592-g267f7v0uhqb6ep7h4hajevhhe5ev4dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQlc-9LnhG1eivAPcVRSDLXEwNhaL-sRk',
    appId: '1:499402471592:ios:327118316677bcfacf2a9d',
    messagingSenderId: '499402471592',
    projectId: 'bnch-9456f',
    databaseURL: 'https://bnch-9456f-default-rtdb.firebaseio.com',
    storageBucket: 'bnch-9456f.appspot.com',
    iosClientId: '499402471592-37hdvaef5act3vdh3iii4bmejv6hv38j.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
